<?php
declare(strict_types=1);
require_once __DIR__ . '/_init.php';
$db = database_connection();
$statuses = ['New', 'Contacted', 'Quoted', 'Won', 'Lost'];
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $id = filter_var($_POST['id'] ?? null, FILTER_VALIDATE_INT);
    $status = (string) ($_POST['status'] ?? '');
    if (!csrf_valid($_POST['csrf_token'] ?? null) || !$id || !in_array($status, $statuses, true)) $error = 'The update could not be applied.';
    else {
        $stmt = $db->prepare('UPDATE leads SET status = :status WHERE id = :id');
        $stmt->execute([':status' => $status, ':id' => $id]);
        header('Location: /admin/index.php?updated=1'); exit;
    }
}
$counts = array_fill_keys($statuses, 0);
foreach ($db->query('SELECT status, COUNT(*) AS total FROM leads GROUP BY status') as $row) $counts[$row['status']] = (int) $row['total'];
$total = array_sum($counts);
$leads = $db->query('SELECT id, created_at, name, phone, email, product, category, quantity, message, status FROM leads ORDER BY created_at DESC, id DESC LIMIT 250')->fetchAll();
$token = csrf_token();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Leads | Print Advertising</title><link rel="icon" href="/images/favicons/favicon.png"><style>
*{box-sizing:border-box}body{margin:0;background:#f7f6fa;color:#191632;font:14px/1.5 Arial,sans-serif}.top{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:14px max(18px,calc((100% - 1240px)/2));background:#191632;color:#fff}.top img{width:155px;max-height:52px;object-fit:contain}.top a{color:#fff}.wrap{width:min(1240px,calc(100% - 32px));margin:26px auto}.stats{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px;margin-bottom:22px}.stat,.tablebox{border:1px solid #e8e5ee;border-radius:10px;background:#fff}.stat{padding:14px}.stat span{display:block;color:#716d7e;font-size:12px}.stat strong{font-size:23px}.tablebox{overflow:auto}.tablebox h1{margin:0;padding:18px;font-size:21px}.table{width:100%;border-collapse:collapse;min-width:850px}.table th,.table td{padding:11px 13px;border-top:1px solid #eeeaf3;text-align:left;vertical-align:top}.table th{font-size:11px;color:#716d7e;text-transform:uppercase;letter-spacing:.04em}.table td small{display:block;color:#716d7e}.table select,.table button{min-height:36px;border:1px solid #ddd8e7;border-radius:5px;background:#fff;padding:6px}.table button{background:#6515d4;color:#fff;border-color:#6515d4;cursor:pointer}.actions{display:flex;gap:5px;flex-wrap:wrap}.details{max-width:250px;white-space:pre-wrap;overflow-wrap:anywhere}.notice{color:#247454}@media(max-width:800px){.stats{grid-template-columns:repeat(3,minmax(0,1fr))}.wrap{margin-top:18px}}@media(max-width:420px){.stats{gap:7px}.stat{padding:10px}.stat strong{font-size:20px}.top img{width:125px}}
</style></head><body><header class="top"><a href="/admin/index.php"><img src="/images/logo.webp" alt="Print Advertising"></a><span><?= escape_html($_SESSION['admin_name'] ?? 'Admin') ?> · <a href="/admin/logout.php">Log out</a></span></header><main class="wrap"><section class="stats" aria-label="Lead totals"><div class="stat"><span>Total leads</span><strong><?= $total ?></strong></div><?php foreach ($statuses as $status): ?><div class="stat"><span><?= escape_html($status) ?></span><strong><?= $counts[$status] ?></strong></div><?php endforeach; ?></section><section class="tablebox"><h1>Recent enquiries <?php if (isset($_GET['updated'])): ?><span class="notice">· Status updated</span><?php endif; ?><?php if ($error): ?><span><?= escape_html($error) ?></span><?php endif; ?></h1><table class="table"><thead><tr><th>Date</th><th>Name</th><th>Phone</th><th>Email</th><th>Product</th><th>Quantity</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php if (!$leads): ?><tr><td colspan="8">No enquiries yet.</td></tr><?php endif; ?><?php foreach ($leads as $lead): $digits = preg_replace('/\D+/', '', $lead['phone']); ?><tr><td><?= escape_html(date('Y-m-d H:i', strtotime($lead['created_at']))) ?><small>#<?= (int) $lead['id'] ?></small></td><td><?= escape_html($lead['name']) ?><details><summary>View lead</summary><div class="details"><strong>Category:</strong> <?= escape_html($lead['category'] ?: '—') ?><br><strong>Message:</strong> <?= escape_html($lead['message'] ?: '—') ?></div></details></td><td><a href="tel:<?= escape_html($lead['phone']) ?>"><?= escape_html($lead['phone']) ?></a></td><td><?php if ($lead['email']): ?><a href="mailto:<?= escape_html($lead['email']) ?>"><?= escape_html($lead['email']) ?></a><?php else: ?>—<?php endif; ?></td><td><?= escape_html($lead['product'] ?: $lead['category'] ?: '—') ?></td><td><?= escape_html($lead['quantity'] ?: '—') ?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?= escape_html($token) ?>"><input type="hidden" name="id" value="<?= (int) $lead['id'] ?>"><select name="status" aria-label="Lead status"><?php foreach ($statuses as $status): ?><option<?= $lead['status'] === $status ? ' selected' : '' ?>><?= escape_html($status) ?></option><?php endforeach; ?></select><button type="submit">Save</button></form></td><td><div class="actions"><a href="https://wa.me/<?= escape_html($digits) ?>" target="_blank" rel="noopener">WhatsApp</a></div></td></tr><?php endforeach; ?></tbody></table></section><p>Showing the 250 most recent leads.</p></main></body></html>
